# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsInstructor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_instructor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsStudent',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsTeacher',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_teacher', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('course_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=12)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record_set', to='main.AsStudent')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='authority', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('auth', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_record_set', to='main.AsStudent')),
            ],
        ),
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('grade', models.IntegerField()),
                ('college', models.CharField(blank=True, max_length=16)),
                ('major', models.CharField(blank=True, max_length=25)),
                ('number', models.IntegerField()),
                ('as_instructor_set', models.ManyToManyField(related_name='classs_set', to='main.AsInstructor')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('weeks', models.CharField(max_length=255)),
                ('weekday', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('from_week', models.CharField(max_length=255)),
                ('from_weekday', models.CharField(max_length=255)),
                ('from_course_number', models.CharField(max_length=255)),
                ('goal_week', models.CharField(max_length=255)),
                ('goal_weekday', models.CharField(max_length=255)),
                ('goal_course_number', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('approved', models.CharField(choices=[('approving', '审批中'), ('reject', '被拒绝'), ('pass', '通过')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('approved', models.CharField(choices=[('approving', '审批中'), ('reject', '被拒绝'), ('pass', '通过')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_record_set', to='main.AsStudent')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('course_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('no', models.IntegerField()),
                ('system_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='main.SystemSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', '男'), ('FEMALE', '女')], max_length=6, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomManage',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='classroom_manage', serialize=False, to='main.Classroom')),
                ('password', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseManage',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='course_manage', serialize=False, to='main.Course')),
            ],
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_record_set', to='main.Course'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedule_set', to='main.Classroom'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule_set', to='main.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_set', to='main.AsTeacher'),
        ),
        migrations.AddField(
            model_name='authority',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority', to='main.User'),
        ),
        migrations.AddField(
            model_name='asteacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_teacher', to='main.User'),
        ),
        migrations.AddField(
            model_name='asstudent',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_student_set', to='main.Classs'),
        ),
        migrations.AddField(
            model_name='asstudent',
            name='course_set',
            field=models.ManyToManyField(related_name='as_student_set', to='main.Course'),
        ),
        migrations.AddField(
            model_name='asstudent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_student', to='main.User'),
        ),
        migrations.AddField(
            model_name='asinstructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_instructor', to='main.User'),
        ),
        migrations.AddField(
            model_name='classroomrecord',
            name='classroom_manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_record_set', to='main.ClassroomManage'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='course_manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record_set', to='main.CourseManage'),
        ),
    ]
